import type { PromptRow } from "@/types/database";

const DEFAULT_PROMPTS: PromptRow[] = [
  {
    id: "prompt-1",
    campaign_id: "camp-1",
    visual_plan_id: "vp-1",
    scene_name: "Scene 1 — Hook",
    prompt_type: "hero_image",
    prompt_text: "[Mock NanoBanana prompt — will be generated by LLM]",
    metadata: { style: "photorealistic", aspect_ratio: "16:9" },
    created_at: "2025-12-06T00:00:00Z",
  },
];

type MockStore = { _mockPromptRows?: PromptRow[] };
const g = globalThis as typeof globalThis & MockStore;
if (!g._mockPromptRows) g._mockPromptRows = [...DEFAULT_PROMPTS];
export const mockPromptRows = g._mockPromptRows;
