import type { PromptRow } from "@/types/database";

export const mockPromptRows: PromptRow[] = [
  {
    id: "prompt-1",
    campaign_id: "camp-1",
    visual_plan_id: "vp-1",
    scene_name: "Scene 1 — Hook",
    prompt_type: "hero_image",
    prompt_text: "[Mock NanoBanana prompt — will be generated by LLM]",
    metadata: { style: "photorealistic", aspect_ratio: "16:9" },
    created_at: "2025-12-06T00:00:00Z",
  },
];
