import type { ScriptRow } from "@/types/database";

const DEFAULT_SCRIPTS: ScriptRow[] = [
  {
    id: "script-1",
    campaign_id: "camp-1",
    concept_id: "concept-1",
    version_name: "V1 — Burden Hook",
    duration_seconds: 30,
    full_script: "[Mock 30s script — will be generated by LLM]",
    hook: "What happens to your family when you're gone?",
    body: "[Mock body copy]",
    cta: "Call 1-800-555-0100 right now for your free information kit.",
    metadata: null,
    created_at: "2025-12-03T00:00:00Z",
  },
];

type MockStore = { _mockScriptRows?: ScriptRow[] };
const g = globalThis as typeof globalThis & MockStore;
if (!g._mockScriptRows) g._mockScriptRows = [...DEFAULT_SCRIPTS];
export const mockScriptRows = g._mockScriptRows;
