import type { VoScriptRow } from "@/types/database";

const DEFAULT_VO: VoScriptRow[] = [
  {
    id: "vo-1",
    campaign_id: "camp-1",
    script_id: "script-1",
    tagged_script: "[Mock ElevenLabs-tagged script — will be generated by LLM]",
    voice_profile: "Rachel — warm, maternal, southern accent",
    delivery_notes: "Pacing: medium. Pause after hook. Soften on emotional lines.",
    created_at: "2025-12-04T00:00:00Z",
  },
];

type MockStore = { _mockVoScriptRows?: VoScriptRow[] };
const g = globalThis as typeof globalThis & MockStore;
if (!g._mockVoScriptRows) g._mockVoScriptRows = [...DEFAULT_VO];
export const mockVoScriptRows = g._mockVoScriptRows;
