import type { VoScriptRow } from "@/types/database";

export const mockVoScriptRows: VoScriptRow[] = [
  {
    id: "vo-1",
    campaign_id: "camp-1",
    script_id: "script-1",
    tagged_script: "[Mock ElevenLabs-tagged script — will be generated by LLM]",
    voice_profile: "Rachel — warm, maternal, southern accent",
    delivery_notes: "Pacing: medium. Pause after hook. Soften on emotional lines.",
    created_at: "2025-12-04T00:00:00Z",
  },
];
